# simulating external service we cannot change
# for displaying ambassador pattern
apiVersion: v1
kind: Pod
metadata:
  name: external-app
  labels:
    app: external-app
spec:
  containers:
  - name: nginx-outside
    image: nigelpoulton/nginx-outside:1.0    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: ps-ambassador
spec:
  type: LoadBalancer # just for showing that sth is running
  selector:
    app: ambassador
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
