apiVersion: v1
kind: Pod
metadata:
  name: ps-init
  labels:
    app: initializer
spec:
  initContainers: # has to finish successfully before container below starts
    - name: init-sync-ctr
      image: k8s.gcr.io/git-sync:v3.1.5
      volumeMounts:
        - name: html
          mountPath: /tmp/git
      env:
        - name: GIT_SYNC_REPO
          value: https://github.com/nigelpoulton/ps-sidecar.git
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST
          value: "html"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
  containers:
    - name: web
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx
      volumes:
        - name: html
          emptyDir: {}
