  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: app-settings # for referencing in Pods etc.
    labels:
      app: app-settings
  data:
    enemies: aliens
    lives: "3"
    enemies.cheat: "true"
    enemies.cheat.level: "noGoodRotten"
