apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  labels:
    app: nginx-clusterip
spec:
  type: ClusterIP # type of service
  selector: # pod template labels which the service will apply to
    tier: frontend
  ports: # define container target port and port for the service
    - port: 8080
      targetPort: 80
