apiVersion: v1
kind: Service
metadata:
  name: external-service # other Pods can use this anme to access the external service
spec:
  type: ExternalName # type of service
  externalName: api.acmecorp.com # service will proxy to this domain name, only this needs to be changed if API changes, not others (due to name above)
  ports: # define container target port and port for the service
      - port: 9000
