apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath-socket
spec:
  volumes:
    - name: docker-socket
      hostPath: # talk to specific directory on worker node
        path: /var/run/docker.sock
        type: Socket
  containers:
    - name: docker
      image: docker
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
